// Copyright 2026 az9713. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"


type ContentURLs struct {
	Desktop json.RawMessage `json:"desktop"`
	Mobile json.RawMessage `json:"mobile"`
}

type Coordinates struct {
	Lat float64 `json:"lat"`
	Lon float64 `json:"lon"`
}

type FeaturedArticle struct {
	ContentUrls json.RawMessage `json:"content_urls"`
	Description string `json:"description"`
	Extract string `json:"extract"`
	Thumbnail json.RawMessage `json:"thumbnail"`
	Title string `json:"title"`
}

type FeaturedContent struct {
	Tfa json.RawMessage `json:"tfa"`
}

type OnThisDay struct {
	Births json.RawMessage `json:"births"`
	Deaths json.RawMessage `json:"deaths"`
	Events json.RawMessage `json:"events"`
	Holidays json.RawMessage `json:"holidays"`
	Selected json.RawMessage `json:"selected"`
}

type OnThisDayEvent struct {
	Pages json.RawMessage `json:"pages"`
	Text string `json:"text"`
	Year int `json:"year"`
}

type Problem struct {
	Detail string `json:"detail"`
	Title string `json:"title"`
	Type string `json:"type"`
}

type Summary struct {
	ContentUrls json.RawMessage `json:"content_urls"`
	Coordinates json.RawMessage `json:"coordinates"`
	Description string `json:"description"`
	Dir string `json:"dir"`
	Displaytitle string `json:"displaytitle"`
	Extract string `json:"extract"`
	ExtractHtml string `json:"extract_html"`
	Lang string `json:"lang"`
	Originalimage json.RawMessage `json:"originalimage"`
	Revision string `json:"revision"`
	Thumbnail json.RawMessage `json:"thumbnail"`
	Tid string `json:"tid"`
	Timestamp string `json:"timestamp"`
	Title string `json:"title"`
	Type string `json:"type"`
	WikibaseItem string `json:"wikibase_item"`
}

type Thumbnail struct {
	Height int `json:"height"`
	Source string `json:"source"`
	Width int `json:"width"`
}
