// Copyright 2026 az9713. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFeedCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "feed",
		Short: "Manage feed",
	}

	cmd.AddCommand(newFeedFeaturedCmd(flags))
	cmd.AddCommand(newFeedOnthisdayCmd(flags))
	return cmd
}
