// Copyright 2026 az9713. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newFeedFeaturedCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:         "featured <yyyy> <mm> <dd>",
		Aliases:     []string{"get"},
		Short:       "Returns Wikipedia's featured article, image, and news for a given date.",
		Example:     "  wikipedia-pp-cli feed featured 2026 05 10",
		Annotations: map[string]string{"pp:endpoint": "feed.featured", "pp:method": "GET", "pp:path": "/feed/featured/{yyyy}/{mm}/{dd}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/feed/featured/{yyyy}/{mm}/{dd}"
			path = replacePathParam(path, "yyyy", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("mm is required\nUsage: %s <%s>", cmd.CommandPath(), "mm"))
			}
			path = replacePathParam(path, "mm", args[1])
			if len(args) < 3 {
				return usageErr(fmt.Errorf("dd is required\nUsage: %s <%s>", cmd.CommandPath(), "dd"))
			}
			path = replacePathParam(path, "dd", args[2])
			params := map[string]string{}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "feed", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}

	return cmd
}
