// Copyright 2026 az9713. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newFeedOnthisdayCmd(flags *rootFlags) *cobra.Command {
	var flagType string

	cmd := &cobra.Command{
		Use:         "onthisday <mm> <dd>",
		Short:       "Returns historical events, births, deaths, and holidays for a given calendar date.",
		Example:     "  wikipedia-pp-cli feed onthisday example-value example-value",
		Annotations: map[string]string{"pp:endpoint": "feed.onthisday", "pp:method": "GET", "pp:path": "/feed/onthisday/{type}/{mm}/{dd}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if cmd.Flags().Changed("type") {
				allowedType := []string{"all", "selected", "births", "deaths", "events", "holidays"}
				validType := false
				for _, v := range allowedType {
					if flagType == v {
						validType = true
						break
					}
				}
				if !validType {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "type", flagType, allowedType)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/feed/onthisday/{type}/{mm}/{dd}"
			if len(args) < 2 {
				return usageErr(fmt.Errorf("mm is required\nUsage: %s <%s>", cmd.CommandPath(), "mm"))
			}
			path = replacePathParam(path, "mm", args[1])
			if len(args) < 3 {
				return usageErr(fmt.Errorf("dd is required\nUsage: %s <%s>", cmd.CommandPath(), "dd"))
			}
			path = replacePathParam(path, "dd", args[2])
			path = replacePathParam(path, "type", fmt.Sprintf("%v", flagType))
			params := map[string]string{}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "feed", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagType, "type", "all", "Type of events: all, selected, births, deaths, events, holidays (one of: all, selected, births, deaths, events, holidays)")

	return cmd
}
