// Copyright 2026 az9713. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPageCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "page",
		Short: "Manage page",
	}

	cmd.AddCommand(newPageHtmlCmd(flags))
	cmd.AddCommand(newPageRandomCmd(flags))
	cmd.AddCommand(newPageSummaryCmd(flags))
	return cmd
}
